.TH stops 1 "Jul 20, 2018" "Query Västtrafik to show the incoming vehicles on a stop"
.SH NAME
stops
\- Query Västtrafik to show the incoming vehicles on a stop

.SH SYNOPSIS
stops
.br
stops STOP

.SH DESCRIPTION
This command queries the online API provided by Västtrafik to list the incoming vehicles on the desired stop, and the amount of time before they arrive.
.br
The easier way to use it is to write the name of the stop as parameter.
.br
Alternatively, calling it without parameter will make it use an interactive mode, which can be used to show
suggestions for the names.
.SH "EXAMPLE"
stops stigbergs
.SH "SEE ALSO"
.BR stops(1)
.SH WEB
.BR https://github.com/ltworf/pysttrafik

.SH AUTHOR
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
